# Generated by Django 5.2.1 on 2025-05-21 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('admin_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='Admin', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CrimeType',
            fields=[
                ('crime_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('crime_type_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Criminal',
            fields=[
                ('criminal_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('nationality', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PoliceStation',
            fields=[
                ('station_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('contact_person', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('area_id', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Crime',
            fields=[
                ('crime_id', models.AutoField(primary_key=True, serialize=False)),
                ('crime_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crime_management.crimetype')),
            ],
        ),
        migrations.CreateModel(
            name='Officer',
            fields=[
                ('officer_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('off_rank', models.CharField(blank=True, max_length=50, null=True)),
                ('contact', models.CharField(blank=True, max_length=20, null=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crime_management.policestation')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, max_length=100, null=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crime_management.admin')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('profile_id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(blank=True, max_length=200, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crime_management.user')),
            ],
        ),
        migrations.CreateModel(
            name='FIRDetail',
            fields=[
                ('fir_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('date', models.DateField()),
                ('time', models.TimeField(blank=True, null=True)),
                ('crime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crime_management.crime')),
                ('officer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crime_management.officer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crime_management.user')),
            ],
        ),
        migrations.CreateModel(
            name='CriminalCrime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crime_management.crime')),
                ('criminal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crime_management.criminal')),
            ],
            options={
                'unique_together': {('criminal', 'crime')},
            },
        ),
        migrations.CreateModel(
            name='ProfileCriminal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criminal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crime_management.criminal')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crime_management.profile')),
            ],
            options={
                'unique_together': {('profile', 'criminal')},
            },
        ),
    ]
